export const TIMER_ATTENDANCE_SECONDS: number = GM_getValue('TIMER_ATTENDANCE_SECONDS', 60);
export const TIMER_NOTIFICATION_MINUTES: number = GM_getValue('TIMER_NOTIFICATION_MINUTES', 5);
export const FUN_COMPANY_EMPLOYEE_COUNT: boolean = GM_getValue('FUN_COMPANY_EMPLOYEE_COUNT', false);
