enum SessionKeys {
    SIGN_IN_NOTIFICATION = 'SIGN_IN_NOTIFICATION',
    OFF_WORK_NOTIFICATION = 'OFF_WORK_NOTIFICATION',
    SIGN_OUT_NOTIFICATION = 'SIGN_OUT_NOTIFICATION',
    SIGN_IN_NOTIFICATION_TIMER = 'SIGN_IN_NOTIFICATION_TIMER',
    TODAY_ATTENDANCE_CONTENT_TIMER = 'TODAY_ATTENDANCE_CONTENT_TIMER',
    TODAY_ATTENDANCE_FAVICON_TIMER = 'TODAY_ATTENDANCE_FAVICON_TIMER',
    COMPANY_EMPLOYEE_COUNT = 'COMPANY_EMPLOYEE_COUNT',
}

export default SessionKeys;
