enum SessionKeys {
    COMPANY_NOTIFICATION = 'COMPANY_NOTIFICATION',
    SIGN_OUT_ALREADY_NOTIFICATION = 'SIGN_OUT_ALREADY_NOTIFICATION',
    SIGN_IN_NOTIFICATION = 'SIGN_IN_NOTIFICATION',
    OFF_WORK_NOTIFICATION = 'OFF_WORK_NOTIFICATION',
    SIGN_OUT_NOTIFICATION = 'SIGN_OUT_NOTIFICATION',
    UPDATE_LOG_NOTIFICATION = 'UPDATE_LOG_NOTIFICATION',
    ATTENDANCE_TIMER = 'ATTENDANCE_TIMER',
    AJAX_LEAVE_NOTES = 'AJAX_LEAVE_NOTES',
    AJAX_LEAVE_NOTES_TIMESTAMP = 'AJAX_LEAVE_NOTES_TIMESTAMP',
    AJAX_ANNUAL_LEAVE = 'AJAX_ANNUAL_LEAVE',
    AJAX_ANNUAL_LEAVE_TIMESTAMP = 'AJAX_ANNUAL_LEAVE_TIMESTAMP',
    AJAX_LEAVE_RECEIPT_NOTES = 'AJAX_LEAVE_RECEIPT_NOTES',
    AJAX_LEAVE_RECEIPT_NOTES_TIMESTAMP = 'AJAX_LEAVE_RECEIPT_NOTES_TIMESTAMP',
    AJAX_COMPANY_EMPLOYEE_COUNT = 'AJAX_COMPANY_EMPLOYEE_COUNT',
    AJAX_COMPANY_EMPLOYEE_COUNT_TIMESTAMP = 'AJAX_COMPANY_EMPLOYEE_COUNT_TIMESTAMP',
}

export default SessionKeys;
